version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./web:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
