local status_ok, configs = pcall(require, "nvim-treesitter.configs")
if not status_ok then
    return
end

configs.setup {
  ensure_installed = {
      "lua",
      "bash",
      "diff",
      "dockerfile",
      "gitattributes",
      "gitignore",
      "glsl",
      "go",
      "gomod",
      "gowork",
      "graphql",
      "haskell",
      "html",
      "http",
      "java",
      "javascript",
      "json",
      "json5",
      "kotlin",
      "latex",
      "llvm",
      "make",
      "markdown",
      "ninja",
      "php",
      "phpdoc",
      "python",
      "r",
      "regex",
      "scss",
      "sql",
      "svelte",
      "todotxt",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vue",
      "yaml",
      "cmake",
      "comment",
      "css",
      "c",
      "cpp",
      "rust",
  },
  sync_install = false,
  ignore_install = { "" },
  autopairs = {
    enable = true
  },
  highlight = {
    enable = true,
    disable = { "" },
    additional_vim_regex_highlighting = true,

  },
  indent = { enable = true, disable = { "yaml" } },
}
