apiVersion: v1
kind: Service
metadata:
  name: auth-api-service
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # Not reachable from outside, still has loadbalancig inside cluster
