displays:
  - name: eDP-1
    workspaces: [8,9,0]
  - name: HDMI-1
    workspaces: [1,2,3,4,5,6,7]
    randr_extra_options: "--left-of eDP-1"
  - name: DP-2-8
    workspaces: [1,2,3,4,5,6,7]
    randr_extra_options: "--left-of eDP-1"
