apiVersion: apps/v1
kind: Deployment
metadata: 
  name: simple-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-app
      tier: backend
  template:
    metadata:
      labels:
        app: simple-app
        tier: backend
    spec:
      containers:
        - name: first-node
          image: fmuhic/fudo:v1
          env:
            - name: CONTENT_FILE
              value: /data/file.txt
          volumeMounts:
            - mountPath: /data
              name: production-storage
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
        # - name: second
        #   image: pathToSecondImageOnDockerhub
      volumes:
        - name: pod-storage
          emptyDir: {} # Creates empty dir when pod starts, and keeps it alive until pod dies
        - name: host-storage
          hostPath: # Maps dir on host machine, good if we run pods only on one machine
            path: /data 
            type: DirectoryOrCreate
        - name: production-storage
          persistentVolumeClaim:
            claimName: host-pvc
