return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  lazy = false,
  opts = {
    ensure_installed = {
      "lua",
      "bash",
      "diff",
      "dockerfile",
      "gitattributes",
      "gitignore",
      "glsl",
      "go",
      "gomod",
      "gowork",
      "graphql",
      "haskell",
      "html",
      "http",
      "java",
      "javascript",
      "json",
      "json5",
      "kotlin",
      "latex",
      "llvm",
      "make",
      "markdown",
      "ninja",
      "norg",
      "php",
      "phpdoc",
      "python",
      "r",
      "regex",
      "scss",
      "sql",
      "svelte",
      "todotxt",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vue",
      "yaml",
      "cmake",
      "comment",
      "css",
      "c",
      "cpp",
      "rust"
    },
    autopairs = {
      enable = true
    },
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = true,
    },
    indent = {
      enable = true,
      disable = { "yaml" }
    }
  }
}
